# Classwork 1: Pandas Series and DataFrames

\


# General Instructions:
<b>Read each step carefully.</b> The instructions contain a quick review of the information you need to know for each challenge. <b>Make sure you only modify the areas that specify "YOUR CODE HERE". </b>

<b>Pay attention to detail!</b> In programming, a single typo, a missed comma, a capital letter vs a lower case letter difference matter! They can make or break your code!

<b>Do not attempt to modify or remove the auto-grading cells. Doing so will result in a grade of 0.</b> Their purpose is to give you immediate feedback so you can be sure your work is correct.

<b>Please don't add or remove cells.</b> If you accidentally remove one, you can press Cmd + m + z (in that order) to undo that action, at least on MacOS. Otherwise, you can make a new copy of the activity and start over!


\

\

## Submitting this activity:
1. Complete the required challenges and questions
2. Download the file as a Jupyter Notebook by clicking File -> Download -> Download .ipynb
3. Rename the file into the following format: YOURID_Classwork1.ipynb
4. Upload the file into the appropriate place in Canvas


Run the cell below at least once to load the auto-grading code.

In [ ]:
### Run this cell at least once to install the auto-grading code.
### If you run this more than once, it'll still work but it'll show an error below saying:
### "fatal: destination path 'AIDA-classwork1' already exists and is not an empty directory"

!git clone https://github.com/GzzDany/ADIAclasswork.git

# Getting started with Pandas

In this activity, you'll learn basic pandas concepts such as creating Series and Data Frames.

First, we need to import the pandas module. Thankfully, the package is so popular that Google Colab has it pre-installed, so we don't need to worry about that part.

We'll give it an alias (aka a "name"). Its standard alias is "pd". The following cell will take care of this:

In [1]:
import pandas as pd

Whenever you want to use pandas, you'll need to import it so that the functions stored within that module are loaded in memory for use.

# Creating a pandas Series

Remember: A pandas Series is a one-dimensional array of data with a labeled index.

The data can be of various types, check out the table below:


| Usage | Pandas dtype | Python Type | Example |
| :--| :-- | :-- | :-- |
| Text | object | str or mixed | names, countries, IDs, etc|
| Integers | int64 | int | Whole numbers: -10, 2, 60, 420 |
| Numeric with decimals | float64 | float | Numbers with decimals: 3.1416, 10.1 |
| True or False | bool | bool | Two possible values: True or False|
| Date | datetime64 | NA | Date and time values: 25-02-2024 13:00:00


You can create a Series from a list of values, as an example, let's create a series of fruit names. Run the cell below to see this in action!

In [ ]:
fruits = pd.Series(["apple", "orange", "banana"], name="Fruits")

fruits

In [ ]:
series = pd.Series([1, 2, 3.7, "one"], name="Test")

series

In the code above, we create a Pandas Series with 3 values (apple, orange and banana), and store it in the variable called "fruits".

You can see the index starts from 0 and increases by 1 for each element in the Series, the name displayed at the top and the data type "object" displayed at the bottom, indicating that the series contains text.

When you create a pandas.Series, pandas automatically determines the data type (dtype) based on the values you provide. Since the values in this case were text, pandas sets the data type to "object", which is used for string-based data.

It's important to note that <b>all values in a Series must have the same data type. </b>If you mix different types, pandas will convert them to a common type that can accommodate all values without loss of information.

For example:
* Mixing integers and floats results in all values converted to <b>float</b>, since integers can be represented as floats by adding ".0", but floats cannot be represented as integers without losing information.
* However, if you mix numbers and text, pandas will convert everything to "object" (string format), since text cannot be represented as numeric type.

Data types are an important aspect to consider when storing information both for efficiency and functionality. The data type determines what kind of transformations can be performed on the data later on - such as adding a constant, or multiplying all values by a constant, which you cannot do with text.



Now try it yourself!
1. Make a pandas series of at least 3 names and store it in a variable called "names", representing the names of some people, with the name of the series as "Name".
2. Make a pandas series of at least 3 integers and store it in a variable called "ages", representing the ages of the people in the "names" series, with the name of the series as "Age".
3. Make a pandas series of at least 3 integers and store it in a variable called "heights", representing the height in meters of the people in the "names" series, with the name of the series as "Height". This column should use decimal values!


Run the autograder cell below to ensure your code works properly.

In [10]:
### Your code here:

names = pd.Series(["Dany", "Juan", "Pedro"], name="Name")
ages = pd.Series([4,5,6], name="Age")
heights = pd.Series([1.10,1.20,1.30], name="Height")

In [12]:
### Autograder cell
### DO NOT MODIFY OR DELETE
from ADIAclasswork.autograde_act1 import grade_p1

grade_p1(globals())

Error! The values in your 'names' series should be text!

# Creating DataFrames

A pandas DataFrame is, informally, a table of data with an index and column names.

One way to create a DataFrame is to use a dictionary. You'll cover these useful and versatile data structures in detail in the Python programming module later. For now, just know that a dictionary is defined with curly braces { } and has keys and values associated with a colon (:). In this case, the keys will be column names, and the values will be lists of the values in the column, as shown below:

In [17]:
data_dictionary = {"Fruit":["apple", "orange", "banana"], "Price":[1.2, 0.95, 2.3]}


fruit_prices = pd.DataFrame(data=data_dictionary)

fruit_prices

    Fruit  Price
0   apple   1.20
1  orange   0.95
2  banana   2.30

Notice the index at the far left, and the column names on the top of the DataFrame object.

To recap, the code above created a dictionary with two keys: "Fruits" and "Prices", and their associated values are the lists of fruit names and prices, respectively. You can also avoid the step of creating the dictionary outside and type it directly into the pd.DataFrame function as such:

```
pd.DataFrame(data={"Fruits":["apple", "orange", "banana"], "Prices":[1.20, 0.95, 2.30]})
```


If you want to inspect the data types, you can call the DataFrame as shown below. Run the cell below to show the output of the code.

In [14]:
fruit_prices.dtypes

Fruit        str
Price    float64
dtype: object

Notice that each column name is now in a row and its associated value is the datatype of that column.

Now it's your turn to create a DataFrame.

Make a DataFrame and store it in a variable called "my_dataframe" that includes at least 3 rows and columns, with at least one column of data type "object", "integer" and "float" each. Give your columns meaningful names.

In [29]:
### YOUR CODE HERE


my_dataframe = {"Names":["Adan","Mau","Peter"], "Ages":[18,19,20], "Heights":[1.10,1.20,1.30]}

my_dataframe = pd.DataFrame(data=my_dataframe)

my_dataframe

   Names  Ages  Heights
0   Adan    18      1.1
1    Mau    19      1.2
2  Peter    20      1.3

In [28]:
### Autograder cell
### DO NOT MODIFY OR DELETE

from ADIAclasswork.autograde_act1 import grade_p2

grade_p2(globals())

Error! Your DataFrame doesn't contain a column of Data Type object. Make sure you include a text column.
Error! Your DataFrame doesn't contain a column of Data Type int64. Make sure you include a whole number column.

You're done with this activity! Great job. You should now have a basic understanding of pandas Series, data types and DataFrames. We'll dive deeper into manipulating DataFrames with more detail in the next activities, so make sure to clarify any doubts or questions about this!


Upload your work to cavas according to the instructions at the top!