# Activity 6: Derived Columns

In this activity, we'll obtain new columns by applying transformations to existing columns. This will help deepen potential analysis later on.

We'll continue using the <b>NYC Taxi dataset</b>, assuming it is already clean (no missing values, no negative values or 0's where there shouldn't be).

## Submitting this activity:
1. Complete the required challenges and questions
2. Download the file as a Jupyter Notebook by clicking File -> Download -> Download .ipynb
3. Rename the file into the following format: YOURID_Classwork6.ipynb
4. Upload the file into the appropriate place in Canvas

Run the cell below at least once to enable the autograder functionality.

In [2]:
!git clone https://github.com/GzzDany/ADIAclasswork.git

from ADIAclasswork.autograde_act5 import *

"git" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

First, let's load the dataset:

In [3]:
import pandas as pd


df = load_dataset()


# Mostrar los datos
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2.0,2024-01-01 00:57:55,2024-01-01 01:17:43,1.0,1.72,1.0,N,186.0,79.0,2.0,17.7,1.0,0.5,0.00,0.0,1.0,22.70,2.5,0.0
1,1.0,2024-01-01 00:03:00,2024-01-01 00:09:36,1.0,1.80,1.0,N,140.0,236.0,1.0,10.0,3.5,0.5,3.75,0.0,1.0,18.75,2.5,0.0
2,1.0,2024-01-01 00:17:06,2024-01-01 00:35:01,1.0,4.70,1.0,N,236.0,79.0,1.0,23.3,3.5,0.5,3.00,0.0,1.0,31.30,2.5,0.0
3,1.0,2024-01-01 00:36:38,2024-01-01 00:44:56,1.0,1.40,1.0,N,79.0,211.0,1.0,10.0,3.5,0.5,2.00,0.0,1.0,17.00,2.5,0.0
4,1.0,2024-01-01 00:46:51,2024-01-01 00:52:57,1.0,0.80,1.0,N,211.0,148.0,1.0,7.9,3.5,0.5,3.20,0.0,1.0,16.10,2.5,0.0

Let's assume that the dataset is clean. For now, it contains no negaive values in "fare_amount", "tip_amount", or "total_amount", nor does it contain values smaller than or equal to 0 in "passenger_count". \
Note: I left potential negative values in "extra" because this column might represent necessary adjustments to price or fares or other reasons.

You can check that these conditions are met using df.describe(), a powerful method for descriptive statistics for each column in the DataFrame. Run the cell below and check it out!

In [4]:
df.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
count,2.723805e+06,2723805,2723805,2.723805e+06,2.723805e+06,2.723805e+06,2.723805e+06,2.723805e+06,2.723805e+06,2.723805e+06,2.723805e+06,2.723805e+06,2.723805e+06,2.723805e+06,2.723805e+06,2.723805e+06,2.723805e+06,2.723805e+06
mean,1.765527e+00,2024-01-17 01:24:18.345768,2024-01-17 01:40:04.158474,1.354729e+00,3.302459e+00,2.035313e+00,1.663723e+02,1.655898e+02,1.185492e+00,1.844257e+01,1.536055e+00,4.967320e-01,3.471288e+00,5.491481e-01,9.999002e-01,2.741167e+01,2.323129e+00,1.463507e-01
min,1.000000e+00,2002-12-31 22:59:39,2002-12-31 23:05:41,1.000000e+00,1.000000e-02,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e-02,-2.500000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.010000e+00,0.000000e+00,0.000000e+00
25%,2.000000e+00,2024-01-09 15:47:19,2024-01-09 16:04:26,1.000000e+00,1.010000e+00,1.000000e+00,1.320000e+02,1.140000e+02,1.000000e+00,8.600000e+00,0.000000e+00,5.000000e-01,1.000000e+00,0.000000e+00,1.000000e+00,1.548000e+01,2.500000e+00,0.000000e+00
50%,2.000000e+00,2024-01-17 10:50:56,2024-01-17 11:09:34,1.000000e+00,1.700000e+00,1.000000e+00,1.620000e+02,1.620000e+02,1.000000e+00,1.280000e+01,1.000000e+00,5.000000e-01,2.800000e+00,0.000000e+00,1.000000e+00,2.015000e+01,2.500000e+00,0.000000e+00
75%,2.000000e+00,2024-01-24 18:49:30,2024-01-24 19:04:47,1.000000e+00,3.130000e+00,1.000000e+00,2.340000e+02,2.340000e+02,1.000000e+00,1.980000e+01,2.500000e+00,5.000000e-01,4.200000e+00,0.000000e+00,1.000000e+00,2.856000e+01,2.500000e+00,0.000000e+00
max,2.000000e+00,2024-02-01 00:01:15,2024-02-01 22:04:34,9.000000e+00,1.540032e+04,9.900000e+01,2.650000e+02,2.650000e+02,4.000000e+00,2.221300e+03,1.425000e+01,4.000000e+00,4.227000e+02,1.159200e+02,1.000000e+00,2.225300e+03,2.500000e+00,1.750000e+00
std,4.236689e-01,NaN,NaN,8.448003e-01,1.232759e+01,9.732463e+00,6.313191e+01,6.916493e+01,4.561622e-01,1.743611e+01,1.795291e+00,4.048159e-02,3.849782e+00,2.125662e+00,8.726085e-03,2.196847e+01,6.410101e-01,4.844536e-01

Let's make new columns that can help us make a better analysis later on.

## 1. Unit Conversion

Remember that new columns can be generated from simple arithmetic operations on existing columns. For example, if we wanted to make a new column that consists of an old column augmented by 5 units, we can simply code:

```
df["NEW_COL"] = df["COL"] + 5
```

In this case, we want to convert the column "trip_distance" from miles to kilometers into a new column called "trip_distance_km".

We'll use the following unit conversion formula:

$$kilometers = miles \times 1.60934 $$

Try it youself!

In [8]:
### YOUR CODE HERE
df["trip_distance_km"] = df["trip_distance"] * 1.60934

In [9]:
### Autograder cell
### DO NOT MODIFY

grade_p1(globals())

Great job!

Now, we'll generate a column with the tip percentage that was given. Calculate the percentage by dividing the tip_amount column by the fare_amount and multiplying by 100, and save those results into a new column called "tip_percentage".

<b>Hint:</b> Don't forget to multiply by 100!

In [13]:
### YOUR CODE HERE
df["tip_percentage"] = (df["tip_amount"] / df["fare_amount"]) * 100

In [14]:
### Autograder cell
### DO NOT MODIFY

grade_p2(globals())

Great job!

## 2. Derived datetime column

Now, we'll extract information about the trip duration, creating a new column called "trip_duration" which contains the amount of <b>minutes</b> the trip lasted.

Remember that when substracting dates, a new <b>timedelta</b> object is created, from which the amount of seconds can be extracted as such:

```
df["NEW_DATETIME_COL"] = (df["DATETIME_COL2"] - df["DATETIME_COL1"]).dt.total_seconds()
```

<b>Hint:</b> Don't forget to divide by 60 to convert seconds into <b>minutes.</b>

In [28]:
### YOUR CODE HERE
df["trip_duration"] = ((df["tpep_dropoff_datetime"] - df["tpep_pickup_datetime"]).dt.total_seconds()) / 60

In [29]:
### Autograder cell
### DO NOT MODIFY

grade_p3(globals())

Great job!

Another relevant aspect of a datetime object is the time of day in which the trip started, so we'll create a new column for the hour, specifically.

If we wanted to extract the seconds of a datetime column into a new column, we would use:

```
df["seconds"] = df["DATETIME_COL"].dt.seconds
```

For your convenience, you can find how to extract other units [in this link](https://pandas.pydata.org/docs/reference/api/pandas.Series.dt.date.html) - You'll have to scroll way down in the left bar, but they're there!

Create a new column called "hour_start" that stores the hour when the trip started.

In [31]:
### YOUR CODE HERE

df["hour_start"] = df["tpep_pickup_datetime"].dt.hour

In [32]:
### Autograder cell
### DO NOT MODIFY

grade_p4(globals())

Great job!

We can also obtain the weekday name and store it in another column. Create a new column called "weekday" with this information. You can use .dt.day_name() <b><- with parenthesis!</b>

In [33]:
### YOUR CODE HERE
df["weekday"] = df["tpep_pickup_datetime"].dt.day_name()

In [34]:
### Autograder cell
### DO NOT MODIFY

grade_p5(globals())

Great job!

## 3. A derived column from derived columns (so meta)

Now that we have the trip duration and its distance, why shouldn't we calculate the trip's average speed? Let's get to work!

Remember: $$ speed = \frac{distance}{time} $$

Calculate the average trip speed <b>in kilometers/hour</b> into a new column called "average_speed".

<b>Note:</b> You'll have to convert the trip duration from minutes into hours! You can add a new column with the duration in hours, or you can directly calculate it by dividing the trip duration column by 60.

In [44]:
### YOUR CODE HERE

df["average_speed"] = df["trip_distance_km"] / (df["trip_duration"] / 60)

In [45]:
### Autograder cell
### DO NOT MODIFY

grade_p6(globals())

Great job!

## 4. Creating categorical columns

Let's categorize trips based on their distance. Let's say that a trip that is over 5 km in distance is considered "long" and "short" otherwise.

Create a new column called "length_category" with this information. Remember that you can apply a function to a column in a DataFrame using the .apply method and passing over the name of the pre-defined function. Here's an example:

```
def my_func(value):
  if value == 0:
    return "Zero"
  elif value > 0:
    return "Positive"
  else:
    return "Negative"

df["NEW_COL"] = df["COL"].apply(my_func)
```

I suggest in this case to define a function called "categorize_length" and then apply it to the "trip_distance_km" column.

In [46]:
### YOUR CODE HERE

### Define your function to categorize length here:
def categorize_length(length):
  if length > 5:
    return "long"
  else:
    return "short"
  pass

### Apply your function to create a new column using .apply() here:
df["length_category"] = df["trip_distance_km"].apply(categorize_length)

In [47]:
### Autograder cell
### DO NOT MODIFY

grade_p7(globals())

Great job!

Phew!

Let's practice this one more time.

The time of day can be useful to group trips based on whether they happened during the "morning" (from 6 to 11), "afternoon" (12 to 20), "night" (21 to 23) and "late night" (0 to 5).

Create a column called "time_of_day" with this information.

Remmeber to pre-define your function and then apply it!

In [56]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,Airport_fee,NEW_trip_distance,trip_distance_km,tip_percentage,trip_duration,hour_start,weekday,average_speed,length_category,time_of_day
0,2.0,2024-01-01 00:57:55,2024-01-01 01:17:43,1.0,1.72,1.0,N,186.0,79.0,2.0,...,0.0,2.768065,2.768065,0.000000,19.800000,0,Monday,8.388075,short,late night
1,1.0,2024-01-01 00:03:00,2024-01-01 00:09:36,1.0,1.80,1.0,N,140.0,236.0,1.0,...,0.0,2.896812,2.896812,37.500000,6.600000,0,Monday,26.334655,short,late night
2,1.0,2024-01-01 00:17:06,2024-01-01 00:35:01,1.0,4.70,1.0,N,236.0,79.0,1.0,...,0.0,7.563898,7.563898,12.875536,17.916667,0,Monday,25.330263,long,late night
3,1.0,2024-01-01 00:36:38,2024-01-01 00:44:56,1.0,1.40,1.0,N,79.0,211.0,1.0,...,0.0,2.253076,2.253076,20.000000,8.300000,0,Monday,16.287296,short,late night
4,1.0,2024-01-01 00:46:51,2024-01-01 00:52:57,1.0,0.80,1.0,N,211.0,148.0,1.0,...,0.0,1.287472,1.287472,40.506329,6.100000,0,Monday,12.663659,short,late night

In [61]:
### YOUR CODE HERE

### Define your function here:
def categorize_time_of_day(hour):
   if hour >= 0 and hour < 6:
    return "late night"
   elif hour > 5 and hour < 12:
    return "morning"
   elif hour > 11 and hour < 21:
      return "afternoon"
   elif hour > 20 and hour < 24:
      return "night"
pass


### Apply your function to create a new column using .apply() here:
df["time_of_day"] = df["hour_start"].apply(categorize_time_of_day)

In [62]:
### Autograder cell
### DO NOT MODIFY

grade_p8(globals())

Great job!