# Activity 7: Loading data and Filtering, Indexing and Selecting

In this activity, you'll practice loading data from a .csv file and some more advanced filtering and indexing techniques to analyze data.

## Submitting this activity:
1. Complete the required challenges and questions
2. Download the file as a Jupyter Notebook by clicking File -> Download -> Download .ipynb
3. Rename the file into the following format: YOURID_Classwork6.ipynb
4. Upload the file into the appropriate place in Canvas

Run the cell below at least once to enable the autograder functionality.

In [1]:
!git clone https://github.com/GzzDany/ADIAclasswork.git

from ADIAclasswork.autograde_act6 import *

"git" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

First, download you need to load the dataset from the .csv file, which you can find on Canvas in the instructions for this activity. Upload it as a file to this Collab and load it using pd.read_csv(). Store the DataFrame in a variable called "df"

Feel free to inspect the dataset with .head() or .describe() to get information on its structure again!

<b>Note:</b> Don't forget to import pandas with its standard alias "pd"!

In [1]:
### YOUR CODE HERE
import pandas as pd

df = pd.read_csv("nyc_taxi_data.csv")

### Load the dataset:
df.head()
### Convert datetime columns into datetime objects:
datetime = ("tpep_pickup_datetime", "tpep_dropoff_datetime")
for column in datetime:
    df[column] = pd.to_datetime(df[column], format="%Y-%m-%d %H:%M:%S")

df.dtypes

VendorID                          int64
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag                  str
PULocationID                      int64
DOLocationID                      int64
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
trip_distance_km                float64
tip_percentage                  float64
trip_duration                   float64
hour_start                        int64
weekday                             str
average_speed                   float64
length_category                     str
time_of_day                         str
dtype: object

In [2]:
### Autograder cell
### DO NOT MODIFY
from ADIAclasswork.autograde_act6 import *

grade_p1(globals())

Columns are ok.
I
Error. You did not correctly load the dataframe. Did you convert the pickup and dropoff time columns into datetime objects? These are always read as strings when loading datasets!

First, let's recall some basic indexing. Use the .loc method to find the trip duration (using the column you derived in the previous activity) of the datapoint in the row index 55.

Store your result in a variable called "trip_duration_55"

In [8]:
### YOUR CODE HERE


trip_duration_55 = df.loc[55, "trip_duration"] 
### REPLACE THIS WITH YOUR ANSWER

trip_duration_55

np.float64(10.35)

In [9]:
### Autograder cell
### DO NOT MODIFY

grade_p2(globals())

Great!

Now, what about the information in the datapoint found at the row index number 80 and the column index 5?

Use .iloc since you're using row and column <i>positions</i> rather than their names. Store your answer in a variable called "data_80_5"

In [10]:
### YOUR CODE HERE

data_80_5 = df.iloc[80, 5]
### REPLACE THIS WITH YOUR ANSWER

data_80_5

np.float64(1.0)

In [11]:
### Autograder cell
### DO NOT MODIFY

grade_p3(globals())

Great!

## Finding indices of certain datapoints

Now let's find the indices of all trips with a passenger count grater than 4. Store the list of indices in a variable called "inds_many_passengers".

Recall the .index attribute after filtering to extract only the index values of the trips of interest!

In [17]:
### YOUR CODE HERE

inds_many_passengers = df[df["passenger_count"] > 4].index
### REPLACE THIS WITH YOUR ANSWER
inds_many_passengers

Index([    53,     83,    126,    134,    190,    209,    226,    244,    291,
          352,
       ...
       271294, 271506, 271534, 271717, 271725, 271755, 271825, 271971, 272222,
       272353],
      dtype='int64', length=5605)

In [18]:
### Autograder cell
### DO NOT MODIFY

grade_p4(globals())

Good job!

Examine the contents of the variable "inds_many_passengers" and answer: What is the average speed of the trip of the first row with at least 5 passengers? (aka the lowest index in the answer above).

Store your answer into the variable called "speed_first_many_passengers"

In [ ]:
inds_many_passengers[0]

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,congestion_surcharge,Airport_fee,trip_distance_km,tip_percentage,trip_duration,hour_start,weekday,average_speed,length_category,time_of_day
0,1,2024-01-18 21:29:42,2024-01-18 21:48:40,1.0,8.00,1.0,N,140,244,1,...,2.5,0.0,12.874720,22.928994,18.966667,21,Thursday,40.728464,long,night
1,1,2024-01-30 19:37:43,2024-01-30 19:51:58,1.0,2.10,1.0,N,68,161,1,...,2.5,0.0,3.379614,35.570470,14.250000,19,Tuesday,14.229954,short,afternoon
2,1,2024-01-08 10:46:12,2024-01-08 10:59:25,1.0,1.20,1.0,N,186,161,1,...,2.5,0.0,1.931208,14.035088,13.216667,10,Monday,8.767149,short,morning
3,2,2024-01-09 12:09:40,2024-01-09 12:25:22,1.0,1.25,1.0,N,161,141,2,...,2.5,0.0,2.011675,0.000000,15.700000,12,Tuesday,7.687930,short,afternoon
4,2,2024-01-13 13:57:02,2024-01-13 14:05:25,1.0,1.15,1.0,N,142,100,1,...,2.5,0.0,1.850741,28.602151,8.383333,13,Saturday,13.245860,short,afternoon

In [28]:
### YOUR ANSWER HERE

speed_first_many_passengers = df.loc[inds_many_passengers[0], "average_speed"]
### REPLACE THIS WITH YOUR ANSWER
speed_first_many_passengers

np.float64(14.453947609147606)

In [29]:
### Autograder cell
### DO NOT MODIFY

grade_p5(globals())

Good job!

How about finding the index of the trip with the minimum speed? Try that out and store your answer in a variable called "min_speed_index".

Remember the method .idxmin() will give you the index of the minimum element of a column.

In [30]:
### YOUR CODE HERE

min_speed_index = df["average_speed"].idxmin()
 ### REPLACE THIS WITH YOUR ANSWER
min_speed_index

233874

In [31]:
### Autograder cell
### DO NOT MODIFY

grade_p6(globals())

Good job!

If the last one was easy, this one will be a breeze. Now do the same but for the maximum speed. Store your answer in a variable called "max_speed_index".

In [32]:
### YOUR CODE HERE

max_speed_index = df["average_speed"].idxmax()
### REPLACE THIS WITH YOUR ANSWER
max_speed_index

50607

In [33]:
### Autograder cell
### DO NOT MODIFY

grade_p7(globals())

Good job!

Now answer the question: How many passengers were in the trip with the lowest speed? Store your answer in a variable called "passengers_max_speed".

<b>Hint:</b> The .loc method will be useful here!

In [40]:
### YOUR CODE HERE

passengers_max_speed = df.loc[max_speed_index, "passenger_count"]
 ### REPLACE THIS WITH YOUR ANSWER
passengers_max_speed

np.float64(1.0)

In [41]:
### Autograder cell
### DO NOT MODIFY

grade_p8(globals())

Good job!

## Combining multiple conditions

By now, you know how to filter a DataFrame using a single condition. Now we'll combine multiple conditions for filtering.

When combining conditions, it's customary to use the "and" and "or" operators. However, these work for <i>single</i> boolean values. When you're comparing a series of values, you need their bit-wise counterparts & (for "and") and | (for "or").

For example, let's say I wanted to filter products with a price larger than 10, or with a discount < 0.1. I could achieve this with:

```
df[(df["price"]>10) | (df["discount"] <0.1)]
```

Since this operation creates a new DataFrame, I could then chain familiar methods such as .shape, .mean(), etc to get more information.

In this exercise, you need to find out how many trips had an average speed between 2 and 3 (not including either). You can achieve this in two different ways:
1. Filtering the DataFrame and chaining the .shape attribute
2. Combining the masks (boolean conditions) and then chaining the .sum() method.

I highly encourage you to use both methods to verify that you do indeed get the same answer!

Store your answer in a variable called num_speed_2_3.

In [46]:
### YOUR CODE HERE:
num_speed_2_3 = df[(df["average_speed"]>=2) & (df["average_speed"] <= 3)]
### Try with filtering and .shape
num_speed_2_3

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,congestion_surcharge,Airport_fee,trip_distance_km,tip_percentage,trip_duration,hour_start,weekday,average_speed,length_category,time_of_day
645,2,2024-01-16 09:55:27,2024-01-16 10:47:24,2.0,1.10,1.0,N,186,161,1,...,2.5,0.0,1.770274,27.538071,51.950000,9,Tuesday,2.044590,short,morning
741,1,2024-01-06 13:31:15,2024-01-06 14:06:46,1.0,1.00,99.0,N,139,38,1,...,0.0,0.0,1.609340,0.000000,35.516667,13,Saturday,2.718735,short,afternoon
2454,2,2024-01-29 15:12:30,2024-01-29 16:16:21,1.0,1.91,1.0,N,230,193,2,...,2.5,0.0,3.073839,0.000000,63.850000,15,Monday,2.888494,short,afternoon
3340,1,2024-01-25 02:29:32,2024-01-25 02:33:30,1.0,0.10,1.0,N,161,161,2,...,2.5,0.0,0.160934,0.000000,3.966667,2,Thursday,2.434296,short,late night
4258,2,2024-01-30 11:51:19,2024-01-30 13:00:00,1.0,1.85,1.0,N,170,244,2,...,2.5,0.0,2.977279,0.000000,68.683333,11,Tuesday,2.600875,short,morning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269537,2,2024-01-06 00:10:28,2024-01-06 00:11:40,4.0,0.03,1.0,N,4,4,1,...,2.5,0.0,0.048280,0.000000,1.200000,0,Saturday,2.414010,short,late night
270794,2,2024-01-15 17:43:00,2024-01-15 19:02:44,1.0,2.44,1.0,N,246,48,1,...,2.5,0.0,3.926790,21.355932,79.733333,17,Monday,2.954942,short,afternoon
271438,2,2024-01-24 12:39:14,2024-01-24 13:08:19,1.0,0.86,1.0,N,141,229,1,...,2.5,0.0,1.384032,4.291845,29.083333,12,Wednesday,2.855310,short,afternoon
272160,2,2024-01-23 14:54:14,2024-01-23 14:56:42,1.0,0.07,1.0,N,230,161,4,...,2.5,0.0,0.112654,0.000000,2.466667,14,Tuesday,2.740228,short,afternoon
272273,2,2024-01-25 12:25:49,2024-01-25 12:51:52,1.0,0.76,1.0,N,162,163,2,...,2.5,0.0,1.223098,0.000000,26.050000,12,Thursday,2.817117,short,afternoon

In [50]:
### Try combining masks and .sum()
mask1 = df["average_speed"]>2
mask2 = df["average_speed"]<3
filtered_df = df[mask1 & mask2]

(mask1 & mask2).sum()

np.int64(307)

In [48]:
### YOUR ANSWER HERE

num_speed_2_3 = 307### REPLACE THIS WITH YOUR ANSWER

In [49]:
### Autograder cell
### DO NOT MODIFY

grade_p9(globals())

Good job!

What's the average fare_amount of the trips provided by Vendor 1 with a trip distance of at least 3 km?

Save your answer into a variable called "mean_fare_vendor1".

<b>Hint:</b> You need to filter the DataFrame using both conditions and then select the fare_amount column and chain the .mean() method.

In [55]:
### YOUR CODE HERE


mask1 = df["VendorID"] == 1
mask2 = df["trip_distance_km"]>=3
mean_fare_vendor1 = df[mask1 & mask2]["fare_amount"].mean()

 ### REPLACE THIS WITH YOUR ANSWER
mean_fare_vendor1

np.float64(27.659024081115334)

In [56]:
### Autograder cell
### DO NOT MODIFY

grade_p10(globals())

Good job!